# Generated by Django 3.0.4 on 2020-04-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='login user')),
                ('password', models.CharField(max_length=35, verbose_name='password user')),
                ('email', models.CharField(max_length=40, verbose_name='email user')),
                ('rating', models.IntegerField(verbose_name='rating user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author comment')),
                ('text', models.TextField(verbose_name='Text comment')),
                ('likes', models.BigIntegerField(verbose_name='Likes comment')),
                ('dislikes', models.BigIntegerField(verbose_name='Dislikes comment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author question')),
                ('title', models.CharField(max_length=200, verbose_name='Title question')),
                ('text', models.TextField(verbose_name='Text question')),
                ('likes', models.BigIntegerField(verbose_name='Likes question')),
                ('dislikes', models.BigIntegerField(verbose_name='Dislikes question')),
                ('dateTime', models.DateTimeField(verbose_name='Publication date')),
                ('tags', models.ManyToManyField(to='app.Tag', verbose_name='list of tags')),
            ],
        ),
        migrations.CreateModel(
            name='LikeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
                ('users', models.ManyToManyField(to='app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment')),
                ('users', models.ManyToManyField(to='app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DisLikeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
                ('users', models.ManyToManyField(to='app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DisLikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment')),
                ('users', models.ManyToManyField(to='app.Client')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
