# Generated by Django 3.0.4 on 2020-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating user'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=128, unique='true', verbose_name='Tag'),
        ),
    ]
