# Generated by Django 3.0.4 on 2020-04-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
