# Generated by Django 3.0.4 on 2020-04-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200406_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislikecomment',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dislikequestion',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
