# Generated by Django 3.0.4 on 2020-04-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200406_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
    ]
