# Generated by Django 3.0.4 on 2020-04-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200406_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikecomment',
            old_name='question',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='question',
            new_name='comment',
        ),
    ]
